### ISSUE TITLE
PAT乙级1-5签到贴

### ISSUE THREAD

**Issue by hehanlin** [patMatch/pat_match#6]
做完1-5题的同学来签到哈，其中不会的，或者有问题的在此贴提问，讨论。

**Comment by hehanlin** [comment]
![_ _20180116145015](https://user-images.githubusercontent.com/10463663/34975516-19aa9342-facd-11e7-87a1-c5cd2a57e999.png)

**Comment by zhangGaoYu** [comment]
求助，1003没看懂

**Comment by ann-zhgy** [comment]
![image](https://user-images.githubusercontent.com/34295225/35041354-6db88604-fbbf-11e7-95ae-07bfdfba6ce3.png)

**Comment by GongTaoYi** [comment]
![3 vn ewhv _1x 8o yw3 w](https://user-images.githubusercontent.com/25428768/35081635-3c8ee8de-fc50-11e7-8774-1f9c5c9ddaad.png)
